name: python-lint

on: [push, pull_request]

jobs:
  lint-terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2  
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        source: "src"
        mypy-options: "--ignore-missing-imports --show-error-codes"
        pylint-options: "--rcfile=setup.cfg"
        isort-options: "-w 100"
        django: true    