name: yaml lint

on: push

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-kubectl@v2.0
    - uses: azure/k8s-lint@v1
      with:
        lintType: dryrun
        manifests: |
        WeatherFrontend/deployment.yml
        WeatherFrontend/service.yml